Ms 3628 exception handling
DBCDK/set-ddf-cover-service pull request #1
Opened 2022-05-10 08:23 UTC by JensGroenborgAndersen

Added exception handler and the corresponding tests

2022-05-10 09:08 UTC, atmdbc requested changes

2022-05-10 09:08 UTC, atmdbc commented on src/test/java/dk/dbc/setddfcover/AbstractContainerTest.java
> +import static com.github.tomakehurst.wiremock.client.WireMock.*;
Vi har en regel om at vi aldrig anvender stjerne imports. Det er en af de eneste settings i IntelliJ som vi ændre.

2022-05-10 09:08 UTC, atmdbc commented on src/test/java/dk/dbc/setddfcover/CoverResourceIT.java
> +
Jeg kunne godt tænke mig en test hvor der sendes forkert formatteret JSON til servicen.

2022-05-10 12:54 UTC, JensGroenborgAndersen commented on src/test/java/dk/dbc/setddfcover/AbstractContainerTest.java
> +import static com.github.tomakehurst.wiremock.client.WireMock.*;
done

2022-05-10 12:55 UTC, JensGroenborgAndersen commented on src/test/java/dk/dbc/setddfcover/CoverResourceIT.java
> +
Det er ikke lykkes mig at exception handleren til at spise fejl som jersey serializeren smider. De kommer stadig ud i plaintext.

2022-05-10 13:08 UTC, atmdbc approved these changes

2022-05-11 08:26 UTC, hwhadbc commented on src/test/java/dk/dbc/setddfcover/CoverResourceIT.java
> +            assertThat("has expected message", body, containsString("<message>HTTP 406 Not Acceptable</message>"));
Det er en rigtig fin løsning methinks...

2022-05-11 08:26 UTC, hwhadbc approved these changes

2022-05-11 08:26 UTC, merged